version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: frontend.Dockerfile
    restart: always
    ports:
      - "8080:8080"
  broker:
    build:
      context: ./broker
      dockerfile: broker.Dockerfile
    restart: always
    ports:
      - "8081:8081"
  auth:
    build:
      context: ./auth
      dockerfile: auth.Dockerfile
    restart: always
    ports:
      - "8082:8082"
