version: '3'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: frontend.Dockerfile
    restart: always
    ports:
      - "8080:80"
  broker:
    build:
      context: ./broker
      dockerfile: broker.Dockerfile
    restart: always
    ports:
      - "8081:80"